Repository MicrosoftDocs/ATADocs, pull requests merged in 2018-10, with the labels that each got.

#133 From private repo
  .openpublishing.publish.config.json
  ATADocs/suspicious-activity-guide.md
  ATPDocs/TOC.md
  ATPDocs/atp-advanced-audit-policy.md
  ATPDocs/atp-architecture.md
  ATPDocs/atp-capacity-planning.md
  ATPDocs/atp-health-center.md
  ATPDocs/atp-multi-forest.md
  ATPDocs/atp-prerequisites.md
  ATPDocs/atp-privacy-compliance.md
  ATPDocs/atp-resources.md
  ATPDocs/atp-role-groups.md
  ATPDocs/atp-silent-installation.md
  ATPDocs/atp-support.md
  ATPDocs/atp-technical-faq.md
  ATPDocs/atp-whats-new.md
  ATPDocs/cef-format-sa.md
  ATPDocs/configure-event-collection.md
  ATPDocs/configure-event-forwarding.md
  ATPDocs/configure-port-mirroring.md
  ATPDocs/configure-proxy.md
  ATPDocs/entity-profiles.md
  ATPDocs/excluding-entities-from-detections.md
  ATPDocs/install-atp-step1.md
  ATPDocs/install-atp-step2.md
  ATPDocs/install-atp-step3.md
  ATPDocs/install-atp-step4.md
  ATPDocs/install-atp-step5.md
  ATPDocs/install-atp-step6-vpn.md
  ATPDocs/install-atp-step7.md
  ATPDocs/install-atp-step8-samr.md
  ATPDocs/integrate-wd-atp.md
  ATPDocs/investigate-entity.md
  ATPDocs/media/atp-architecture-topology.png
  ATPDocs/modifying-atp-config-dcpassword.md
  ATPDocs/monitoring-alerts.md
  ATPDocs/notifications.md
  ATPDocs/reports.md
  ATPDocs/sensitive-accounts.md
  ATPDocs/sensor-update.md
  ATPDocs/setting-syslog.md
  ATPDocs/suspicious-activity-guide.md
  ATPDocs/troubleshooting-atp-known-issues.md
  ATPDocs/troubleshooting-atp-using-logs.md
  ATPDocs/use-case-lateral-movement-path.md
  ATPDocs/validate-port-mirroring.md
  ATPDocs/what-is-atp.md
  ATPDocs/working-with-suspicious-activities.md
  ATPDocs/workspace-portal.md
Labels: Change sent to author, azure-advanced-threat-protection/svc, do-not-merge

#132 Updated index.md
  ATADocs/index.md
Labels: Change sent to author, do-not-merge

#137 From private repo
  ATPDocs/atp-prerequisites.md
Labels: Change sent to author, azure-advanced-threat-protection/svc, do-not-merge

#138 From private repo
  ATADocs/ata-resources.md
  ATADocs/ata-update-1.5-migration-guide.md
  ATADocs/configure-port-mirroring.md
  ATADocs/troubleshooting-ata-known-errors.md
  ATPDocs/TOC.md
  ATPDocs/atp-whats-new.md
  ATPDocs/configure-event-forwarding.md
  ATPDocs/install-atp-step5.md
  ATPDocs/integrate-wd-atp.md
  ATPDocs/media/atp-configuration-wd.png
  ATPDocs/media/enable-integration.png
  ATPDocs/media/wd-atp-enable.png
  ATPDocs/monitored-activities.md
  ATPDocs/notifications.md
  ATPDocs/what-is-atp.md
Labels: Change sent to author, azure-advanced-threat-protection/svc, do-not-merge

#139 From private repo
  ATADocs/configure-event-collection.md
  ATADocs/install-ata-step5.md
  ATADocs/install-ata-step6.md
  ATADocs/modifying-ata-center-configuration.md
  ATADocs/setting-ata-alerts.md
  ATPDocs/cef-format-sa.md
  ATPDocs/configure-event-forwarding.md
  ATPDocs/monitored-activities.md
  ATPDocs/suspicious-activity-guide.md
Labels: Change sent to author, azure-advanced-threat-protection/svc, do-not-merge

#140 Fix ata-architecture.md tables.
  ATADocs/ata-architecture.md
Labels: Change sent to author, advanced-threat-analytics/prod, ready-to-merge

#142 From private repo
  ATADocs/install-ata-step1.md
  ATADocs/install-ata-step4.md
  ATPDocs/TOC.md
  ATPDocs/atp-activities-search.md
  ATPDocs/atp-technical-faq.md
  ATPDocs/atp-whats-new.md
  ATPDocs/install-atp-step1.md
  ATPDocs/media/activities-filter.png
  ATPDocs/media/atp-report-icon.png
  ATPDocs/media/sched-report1.png
  ATPDocs/reports.md
  ATPDocs/suspicious-activity-guide.md
Labels: Change sent to author, azure-advanced-threat-protection/svc, do-not-merge
