Repository MicrosoftDocs/ATADocs, pull requests merged in 2018-11, with the labels that each got.

#143 From private repo
  ATADocs/troubleshooting-ata-known-errors.md
  ATPDocs/atp-prerequisites.md
  ATPDocs/cef-format-sa.md
  ATPDocs/setting-syslog.md
Labels: Change sent to author, azure-advanced-threat-protection/svc, do-not-merge

#144 From private repo
  ATADocs/troubleshooting-ata-known-errors.md
Labels: Change sent to author, advanced-threat-analytics/prod, do-not-merge

#147 From private repo
  ATADocs/configure-event-collection.md
  ATADocs/install-ata-step4.md
  ATADocs/install-ata-step5.md
  ATPDocs/TOC.md
  ATPDocs/atp-whats-new.md
  ATPDocs/cef-format-sa.md
  ATPDocs/configure-event-forwarding.md
  ATPDocs/excluding-entities-from-detections.md
  ATPDocs/install-atp-step6-vpn.md
  ATPDocs/known-issues.md
  ATPDocs/media/dns-auto-exclusions.png
  ATPDocs/media/exclusions.png
  ATPDocs/setting-syslog.md
  ATPDocs/suspicious-activity-guide.md
Labels: do-not-merge

#148 From private repo
  ATPDocs/atp-advanced-audit-policy.md
Labels: Change sent to author, azure-advanced-threat-protection/svc, do-not-merge

#150 From private repo
  ATADocs/troubleshooting-ata-using-ata-database.md
  ATPDocs/atp-whats-new.md
  ATPDocs/cef-format-sa.md
  ATPDocs/known-issues.md
  ATPDocs/suspicious-activity-guide.md
Labels: Change sent to author, azure-advanced-threat-protection/svc, do-not-merge

#151 From private repo
  ATPDocs/cef-format-sa.md
Labels: Change sent to author, azure-advanced-threat-protection/svc, do-not-merge

#153 From private repo
  ATADocs/configure-event-collection.md
  ATADocs/modifying-ata-center-configuration.md
  ATPDocs/TOC.md
  ATPDocs/atp-whats-new.md
  ATPDocs/cef-format-sa.md
  ATPDocs/install-atp-step4.md
  ATPDocs/investigate-lateral-movement-path.md
  ATPDocs/media/atp-lateral-non-sensitive.png
  ATPDocs/media/atp-lmp-activities.png
  ATPDocs/media/atp-lmp-complete.png
  ATPDocs/media/atp-lmp.png
  ATPDocs/media/atp-view-different-date.png
  ATPDocs/media/lateral-movement-path-tab.png
  ATPDocs/media/reports.png
  ATPDocs/reports.md
  ATPDocs/suspicious-activity-guide.md
  ATPDocs/use-case-lateral-movement-path.md
Labels: Change sent to author, azure-advanced-threat-protection/svc, do-not-merge

#154 From private repo
  ATPDocs/TOC.md
  ATPDocs/cef-format-sa.md
  ATPDocs/configure-event-forwarding.md
Labels: Change sent to author, azure-advanced-threat-protection/svc, do-not-merge
