Repository MicrosoftDocs/ATADocs, pull requests merged in 2023-05, with the labels that each got.

#614 Correct remediation suggestion for "Identity theft using Pass-the-Ticket attack
  ATADocs/suspicious-activity-guide.md
Labels: Change sent to author, do-not-merge, qualifies-for-auto-merge, advanced-threat-analytics/svc

#615 Incorrect TID T1334.005 changed to T1134.005
  ATPDocs/persistence-privilege-escalation-alerts.md
Labels: Change sent to author, ready-to-merge, qualifies-for-auto-merge, aq-pr-triaged, microsoft-defender-for-identity/svc

#618 Update configure-windows-event-collection.md: Order of Permissions
  ATPDocs/configure-windows-event-collection.md
Labels: Change sent to author, do-not-merge, qualifies-for-auto-merge, microsoft-defender-for-identity/svc

#627 5/29/2023 PM Publish
  ATPDocs/directory-service-accounts.md
  ATPDocs/health-alerts.md
  ATPDocs/manage-security-alerts.md
  ATPDocs/media/health-alerts/healthissues.png
  ATPDocs/media/lmp-new.png
  ATPDocs/media/view-different-date-new.png
  ATPDocs/monitored-activities.md
  ATPDocs/prerequisites.md
  ATPDocs/quick-installation-guide.md
  ATPDocs/security-assessment-laps.md
  ATPDocs/toc.yml
  ATPDocs/understand-lateral-movement-paths.md
  ATPDocs/what-is.md
  ATPDocs/whats-new-archive.md
  ATPDocs/whats-new.md
Labels: Change sent to author, do-not-merge, microsoft-defender-for-identity/svc, needs-human-review
